// Shared same-save/same-camera D055 before/after evidence; QA never deploys.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import{createHash}from'node:crypto';import{pathToFileURL}from'node:url';
import{ROOT,withBrowser}from'./cdp.mjs';import{pageSession}from'./smoke-d011.mjs';import{tapD053}from'./d053-capture.mjs';import{D053_TOOL_IDS}from'./d053-scenes.mjs';
import{D054_SNAPSHOT,d054World,d054Snapshot}from'./d054-capture.mjs';import{D054_LAYOUT}from'./d054-layout-probe.mjs';
import{D055_BASELINE,D055_VIEWS,D055_CAMERA,D055_SITE,D055_TOOLS,d055ReviewCode}from'./d055-scenes.mjs';
const J=JSON.stringify,hash=x=>createHash('sha256').update(typeof x==='string'||Buffer.isBuffer(x)?x:J(x)).digest('hex');
export async function captureD055({phase='before',outDir=path.join(ROOT,'scratch/d055-'+phase)}={}){
 fs.mkdirSync(outDir,{recursive:true});const code=d055ReviewCode(),report={phase,baseline:D055_BASELINE,qualification:'Synthetic authored save only for fixed review pictures. Not naturally played. Real native Chrome input; touch emulation, not Android hardware.',fixtureSha256:hash(code),cases:[],shots:[],passed:false};const write=(f,v)=>fs.writeFileSync(path.join(outDir,f),typeof v==='string'||Buffer.isBuffer(v)?v:J(v,null,2));
 const html=fs.readFileSync(path.join(ROOT,'dist/index.html'));report.htmlSha256=hash(html);if(phase==='before')assert.equal(report.htmlSha256,D055_BASELINE.htmlSha256);write('D055-'+phase+'-index.html',html);write('D055-fixture.code.txt',code);
 try{for(const opt of D055_VIEWS)await withBrowser({width:Math.max(960,opt.W),height:900},async({page,open})=>{
  const p=await pageSession(page,open,opt),item={viewport:opt,checks:[],shots:[],passed:false},check=(name,fn)=>{fn();item.checks.push(name)},tap=selector=>tapD053(p,selector,opt.mobile);
  report.cases.push(item);try{
   await p.open('sample=seed516&clean=1');await p.ev(`__gt.clearSave();localStorage.setItem('gt3d.v1.save',${J(code)})`);await p.open('');
   await p.ev(`__gt.view(${D055_CAMERA.x},${D055_CAMERA.z},${D055_CAMERA.zoom});__gt.setVisT(2.2);__gt.setDayFrac(0)`);assert.ok(await p.waitFor(async()=>!(await p.toasts()).length,6000));await p.frames(2);
   await p.ev(`window.__d055Inputs=[];for(const type of ['pointerdown','pointerup','click','keydown','keyup'])addEventListener(type,e=>__d055Inputs.push({type,trusted:e.isTrusted,target:e.target.id??'',pointerType:e.pointerType??'',key:e.key??''}),true)`);
   const initial=await d054Snapshot(p);write(`D055-${phase}-initial-${p.W}.json`,initial);check('paused exact fixture',()=>{assert.equal(initial.sim.playing,false);assert.equal(initial.sim.day,150);assert.equal(initial.sim.money,3000);assert.equal(initial.technology.rank,2)});
   const take=async stage=>{await p.ev('__gt.setVisT(2.2);__gt.setDayFrac(0)');await p.frames(2);const camera=await p.ev('__gt.cam()'),con=await p.ev('__gt.con()');assert.equal(camera.zoom,D055_CAMERA.zoom);assert.equal(con.visT,2.2);assert.equal(con.dayFrac,0);const filename=`D055-${phase}-${stage}-${p.W}.png`,bytes=Buffer.from((await page.send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false})).data,'base64');assert.equal(bytes.readUInt32BE(16),p.W);assert.equal(bytes.readUInt32BE(20),p.H);assert.ok(bytes.length>10000);write(filename,bytes);const state=await d054Snapshot(p),shot={filename,sha256:hash(bytes),bytes:bytes.length,stage,viewport:opt,camera,visual:{visT:2.2,dayFrac:0},worldSha256:hash(d054World(state))};write(`D055-${phase}-${stage}-${p.W}.json`,state);item.shots.push(shot);report.shots.push(shot);};
   await tap('.tool[data-t="civic"]');const dock=await p.ev(D054_LAYOUT);check('original18 dock tools preserved',()=>{assert.equal(dock.buttons.length,18);assert.equal(dock.rows,3)});item.layout=dock;
   await take('district');await tap('#civicGuide');
   const ids=await p.ev(`[...document.querySelectorAll('#catalog [data-tool]')].map(b=>b.dataset.tool)`);check('catalog baseline or new seven exact',()=>assert.deepEqual(ids.sort(),[...D053_TOOL_IDS,...(phase==='after'?D055_TOOLS:[])].sort()));
   if(phase==='after')await tap('#catalog [data-group="production"]');await take('catalog');await tap('#catalogClose');
   const end=await d054Snapshot(p);check('read-only navigation world unchanged',()=>assert.deepEqual(d054World(end),d054World(initial)));
   item.inputs=await p.ev('__d055Inputs');check('native trusted input',()=>{assert.ok(item.inputs.some(x=>x.type==='click'));assert.ok(item.inputs.every(x=>x.trusted))});check('zero errors external requests',()=>{assert.deepEqual(page.errors,[]);assert.deepEqual(page.requests.filter(u=>!/^(http:\/\/127\.0\.0\.1:\d+\/|data:|blob:|about:)/.test(u)),[])});const layout=await p.ev('({width:innerWidth,scroll:document.documentElement.scrollWidth})');check('no page overflow',()=>assert.ok(layout.scroll<=layout.width));item.passed=true;console.log('PASS D055',phase,p.W,item.checks.length,'checks',item.shots.length,'PNGs');
  }catch(e){item.error=String(e.stack??e);console.error(item.error);try{write(`D055-${phase}-failure-${p.W}.png`,Buffer.from((await page.send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false})).data,'base64'))}catch{}}
 });report.passed=report.cases.length===3&&report.cases.every(c=>c.passed)&&report.shots.length===6;return report;
 }finally{write('D055-'+phase+'-capture.json',report);}
}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){const phase=process.argv.find(x=>x.startsWith('--phase='))?.slice(8)??'before';const r=await captureD055({phase});process.exitCode=r.passed?0:1;}
