// D049 Chrome/CDP. Touch is real trusted browser input, Android is emulated.
// Clipboard outcomes and pagehide are explicitly test-injected, never external shares.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';import {isDeepStrictEqual} from 'node:util';import {pathToFileURL} from 'node:url';
import {ROOT,withBrowser,sleep} from './cdp.mjs';import {pageSession} from './smoke-d011.mjs';import {d048KeyEvents} from './smoke-d048.mjs';
import {D048_CAMERA,D048_BASELINE_CAMERA,D048_SAVE_KEY,D048_QUOTA,D048_VIEWS,d048ReviewCode,d048FixtureManifest} from './d048-scenes.mjs';
const J=JSON.stringify,OUT=path.join(ROOT,'scratch/shots'),sha=x=>createHash('sha256').update(typeof x==='string'||Buffer.isBuffer(x)?x:J(x)).digest('hex');
const same=(a,b,why)=>assert.ok(isDeepStrictEqual(a,b),`${why}: ${sha(a)} != ${sha(b)}`);
const SNAP=`({sim:__gt.sim(),layers:__gt.layers(),buildings:__gt.buildingList(),history:__gt.history(),commission:__gt.simCms(),code:__gt.save(),saved:__gt.saved(),url:location.href,historyLength:history.length})`;
const WORLD=`({sim:__gt.sim(),layers:__gt.layers(),buildings:__gt.buildingList(),history:__gt.history(),commission:__gt.simCms(),code:__gt.save(),lastDay:__gt.lastDay(),dayReport:__gt.dayRep()})`;
const PROBE=`(()=>{window.__d049={mode:'resolve',accesses:[],calls:[],pending:[],touches:[],keys:[],clicks:[]};
 addEventListener('pointerdown',e=>__d049.touches.push({type:e.pointerType,trusted:e.isTrusted}),true);
 addEventListener('keydown',e=>__d049.keys.push({key:e.key,trusted:e.isTrusted}),true);
 addEventListener('click',e=>{if(e.target.closest('#dlgOk'))__d049.clicks.push({trusted:e.isTrusted})},true);
 Object.defineProperty(navigator,'clipboard',{configurable:true,get(){const c=__d049;c.accesses.push(c.mode);if(c.mode==='getterThrows')throw new Error('D049 injected clipboard getter');if(c.mode==='missing')return undefined;if(c.mode==='methodMissing')return {};
 return {marker:'receiver',writeText(text){if(this.marker!=='receiver')throw new Error('D049 lost Clipboard receiver');c.calls.push(text);if(c.mode==='throws')throw new Error('D049 injected synchronous write');if(c.mode==='reject')return Promise.reject(new Error('D049 injected denial'));if(c.mode==='pending')return new Promise((resolve,reject)=>c.pending.push({resolve,reject}));return Promise.resolve();}};}});
})()`;
async function key(page,k,shift=false){for(const e of d048KeyEvents(k,shift))await page.send('Input.dispatchKeyEvent',e);await sleep(80);}
async function load(p){await p.open('sample=seed516&clean=1');await p.ev(`__gt.clearSave();localStorage.setItem(${J(D048_SAVE_KEY)},${J(d048ReviewCode())})`);await p.open('');await p.ev(`__gt.view(${D048_CAMERA.x},${D048_CAMERA.z},${D048_CAMERA.zoom});__gt.setVisT(2.2);__gt.setDayFrac(0)`);await p.ev('__gt.saveNow()');await p.ev('__gt.journalFlush()');await p.ev('__gt.saveNow()');assert.ok(await p.waitFor(async()=>!(await p.toasts()).length,5000));same(await p.ev('__gt.cam()'),D048_BASELINE_CAMERA,'fixed review camera');assert.equal((await p.ev('__gt.sim()')).playing,false);await p.ev(PROBE);}
async function openExport(p){await p.tapBtn('#menuBtn');assert.ok(await p.tapBtn('#menu [data-m="export"]'));assert.equal(await p.ev("document.querySelector('#dlg').hidden"),false);await state(p,'ready');}
async function state(p,phase){assert.ok(await p.waitFor(()=>p.ev(`document.querySelector('#copyStatus').dataset.phase===${J(phase)}`),1500),'expected copy phase '+phase);const s=await p.ev(`(()=>{const e=document.querySelector('#copyStatus'),b=document.querySelector('#dlgOk'),t=document.querySelector('#dlg textarea');return {phase:e.dataset.phase,text:e.textContent,hidden:e.hidden,role:e.getAttribute('role'),live:e.getAttribute('aria-live'),atomic:e.getAttribute('aria-atomic'),disabled:b.getAttribute('aria-disabled'),value:t.value,selection:[t.selectionStart,t.selectionEnd],label:b.textContent};})()`);assert.equal(s.phase,phase);assert.equal(s.hidden,phase==='hidden');assert.equal(s.role,'status');assert.equal(s.live,'polite');assert.equal(s.atomic,'true');assert.equal(s.disabled,String(phase==='pending'));if(phase==='pending')assert.equal(s.label,'複製中…');if(phase==='success')assert.match(s.text,/已複製分享碼/);if(['unsupported','failed'].includes(phase)){assert.match(s.text,/手動複製/);assert.deepEqual(s.selection,[0,s.value.length]);}assert.doesNotMatch(s.text,/已備份|備份成功|已恢復/);return s;}
async function layout(p){const s=await p.ev(`(()=>{const d=document.querySelector('#dlg .card');return {overflow:document.documentElement.scrollWidth>innerWidth,card:d.scrollWidth>d.clientWidth+1,items:['#copyStatus','#dlgOk','#dlgNo'].map(sel=>{const e=document.querySelector(sel),r=e.getBoundingClientRect();return {sel,l:r.left,r:r.right,t:r.top,b:r.bottom,w:r.width,h:r.height,hidden:!!e.closest('[hidden]')};})};})()`);assert.equal(s.overflow,false);assert.equal(s.card,false);for(const r of s.items){assert.equal(r.hidden,false);assert.ok(r.l>=0&&r.r<=p.W+.5&&r.t>=0&&r.b<=p.H+.5,J(r));if(r.sel!=='#copyStatus')assert.ok(r.w>=44&&r.h>=44,J(r));}return s;}
async function mode(p,value){await p.ev(`__d049.mode=${J(value)}`);}
async function resolve(p,index,reject=false){await p.ev(`__d049.pending[${index}].${reject?'reject(new Error("D049 injected late rejection"))':'resolve()'}`);await p.frames(2);}
async function focusLoop(p,page){for(const shift of [false,true])for(let i=0;i<5;i++){await key(page,'Tab',shift);assert.equal(await p.ev("document.querySelector('#dlg').contains(document.activeElement)&&!document.activeElement.closest('[hidden],[inert]')"),true);}}
export async function d049Smoke(browser,log){
 fs.mkdirSync(OUT,{recursive:true});const report={base:'0605e477345652fba037a428ceff460e5bd8bb1f',fixture:{...d048FixtureManifest(),baseline:{commit:'0605e477345652fba037a428ceff460e5bd8bb1f',htmlSha256:'cbd5ea3d1235042b9407769fc7bb1d8535a09f9ea43ef5173d15907be9213cec',captureRun:37538601991}},sessions:[],shots:[],checks:[]};
 const check=(ok,name,detail)=>{report.checks.push({ok,name,detail});log(ok,'D049 '+name,detail);};
 const flush=()=>fs.writeFileSync(path.join(OUT,'D049-evidence.json'),J(report,null,2)+'\n');
 const run=async(name,opt,fn)=>{try{await browser({width:Math.max(opt.W,960),height:900},async({open,page})=>{const p=await pageSession(page,open,opt);await load(p);const shot=async(label)=>{await p.frames(3);await layout(p);same(await p.ev('__gt.cam()'),D048_BASELINE_CAMERA,'shot camera');const bytes=Buffer.from((await page.send('Page.captureScreenshot',{format:'png'})).data,'base64'),file=`D049-${label}-${p.W}x${p.H}.png`;fs.writeFileSync(path.join(OUT,file),bytes);report.shots.push({file,sha256:sha(bytes),width:p.W,height:p.H,camera:await p.ev('__gt.cam()'),state:await p.ev("document.querySelector('#copyStatus').textContent"),codeSha256:sha(await p.ev("document.querySelector('#dlg textarea').value")),simulatedAndroid:true});};
 try{await fn(p,page,shot);check(true,name);}catch(e){check(false,name,e.stack);}
 await page.send('Runtime.evaluate',{expression:'0',returnByValue:true});
 const probe=await p.ev('__d049'),ext=page.requests.filter(u=>!/^(http:\/\/127\.0\.0\.1:\d+\/|data:|blob:|about:)/.test(u));
 check(page.errors.length===0&&ext.length===0,name+' zero console errors and external requests',[...page.errors,...ext].join('\n'));
 const trusted=opt.mobile===false?probe.keys.length>0&&probe.keys.every(x=>x.trusted):probe.touches.length>0&&probe.touches.every(x=>x.trusted&&x.type==='touch');check(trusted,name+' trusted '+(opt.mobile===false?'keyboard':'touch'),J({touches:probe.touches.length,keys:probe.keys.length}));report.sessions.push({name,probe,errors:[...page.errors],external:ext});
 });}catch(e){check(false,name+' browser session',e.stack);}flush();};
 for(const {width:W,height:H}of D048_VIEWS)await run('portrait '+W,{W,H},async(p,page,shot)=>{
  const before=await p.ev(SNAP);assert.equal(sha(before.code),'17e5e5c26e6bc2f29d2c2107c76e2ac370530a195f9ec71132173ea1b7a66c07','exact exported scene matches captured baseline');await openExport(p);assert.equal(await p.ev("document.querySelector('#dlg textarea').value"),before.code);if(W===412)await shot('ready-after');
  await mode(p,W===360?'missing':'resolve');await p.tapBtn('#dlgOk');const phase=W===360?'unsupported':'success';await state(p,phase);await sleep(3000);await state(p,phase);await shot(phase+'-after');
  for(const [m,s]of [['missing','unsupported'],['methodMissing','unsupported'],['getterThrows','failed'],['throws','failed'],['reject','failed'],['resolve','success']]){await mode(p,m);const counts=await p.ev('({accesses:__d049.accesses.length,writes:__d049.calls.length,clicks:__d049.clicks.length})');await p.tapBtn('#dlgOk');await state(p,s);const after=await p.ev('({accesses:__d049.accesses.slice('+counts.accesses+'),writes:__d049.calls.length,clicks:__d049.clicks.slice('+counts.clicks+')})');assert.deepEqual(after.accesses,[m],'each branch actually accessed its selected Clipboard mode');assert.equal(after.writes-counts.writes,['missing','methodMissing','getterThrows'].includes(m)?0:1);assert.deepEqual(after.clicks,[{trusted:true}],'each branch received exactly one real copy click');await layout(p);assert.equal(await p.ev("document.querySelector('#dlg textarea').value"),before.code);if(W===360&&m==='reject')await shot('rejected-after');}
  await mode(p,'pending');const n=await p.ev('__d049.calls.length');await p.tapBtn('#dlgOk');await state(p,'pending');await p.tapBtn('#dlgOk');await p.tapBtn('#dlgOk');assert.equal(await p.ev('__d049.calls.length'),n+1);if(W===412)await shot('pending-after');await focusLoop(p,page);await resolve(p,0);await state(p,'success');await mode(p,'resolve');await p.tapBtn('#dlgOk');assert.equal(await p.ev('__d049.calls.length'),n+2);
  assert.ok((await p.ev('__d049.calls')).every(x=>x===before.code));await p.tapBtn('#dlgNo');await state(p,'hidden');same(await p.ev(SNAP),before,'copy branches must leave full world/save/URL unchanged');
  await openExport(p);await state(p,'ready');if(W===412)await shot('reopened-after');await p.tapBtn('#dlgNo');same(await p.ev(SNAP),before,'reopen is read-only');
 });
 await run('interrupted and interleaved sessions',{W:412,H:860},async(p,page)=>{
  // Introduce a visible existing save error, then retain its exact current state.
  await p.ev(`window.__d049SetItem=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k===${J(D048_SAVE_KEY)})throw new DOMException(${J(D048_QUOTA)},'QuotaExceededError');return __d049SetItem.call(this,k,v);};__gt.saveNow()`);assert.ok(await p.waitFor(async()=>!(await p.toasts()).length,5000));const before=await p.ev(SNAP);
  const inert=()=>p.ev("[...document.querySelectorAll('[inert]')].map(e=>e.id||e.tagName).sort()"),unlocked=await inert();
  for(const how of ['cancel','escape','backdrop','status','pagehide','paste'])for(const reject of [false,true]){
   if(how==='status'){await p.tapBtn('#stats [data-k="unsaved"]');await p.tapBtn('#saveStatusExport');}else await openExport(p);
   await mode(p,'pending');const index=await p.ev('__d049.pending.length');await p.tapBtn('#dlgOk');await state(p,'pending');
   if(how==='escape')await key(page,'Escape');else if(how==='backdrop')await p.tapAt([4,4]);else if(how==='pagehide')await p.ev("dispatchEvent(new PageTransitionEvent('pagehide',{persisted:true}));dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true}))");else await p.tapBtn('#dlgNo');
   await state(p,'hidden');assert.equal(await p.ev("document.querySelector('#dlg').hidden"),true);if(how==='status'){assert.equal(await p.ev("document.querySelector('#saveStatus').hidden"),false);await p.tapBtn('#saveStatusClose');}
   same(await inert(),unlocked,'close releases inert for '+how);
   if(how==='paste'){await p.tapBtn('#menuBtn');await p.tapBtn('#menu [data-m="paste"]');assert.equal(await p.ev("document.querySelector('#dlgTitle').textContent"),'貼上分享碼');await state(p,'hidden');await resolve(p,index,reject);await state(p,'hidden');assert.equal(await p.ev("document.querySelector('#dlgOk').textContent"),'匯入');await p.tapBtn('#dlgNo');}
   else {await openExport(p);await mode(p,'pending');const newer=await p.ev('__d049.pending.length');await p.tapBtn('#dlgOk');const count=await p.ev('__d049.calls.length'),focus=await p.ev('document.activeElement.id||document.activeElement.tagName');await resolve(p,index,reject);await state(p,'pending');assert.equal(await p.ev('document.activeElement.id||document.activeElement.tagName'),focus);await p.tapBtn('#dlgOk');assert.equal(await p.ev('__d049.calls.length'),count);await resolve(p,newer);await state(p,'success');await p.tapBtn('#dlgNo');}
   assert.deepEqual(await p.toasts(),[],'old responses never show stale toast');same(await p.ev(SNAP),before,'interrupted flow is read-only '+how);
  }
  assert.ok(await p.ev('__gt.ui().saveError'),'copying never repairs autosave');
 });
 await run('native keyboard and focus',{W:1280,H:800,mobile:false},async(p,page)=>{
  const before=await p.ev(SNAP);await p.clickBtn('#menuBtn');await p.clickBtn('#menu [data-m="export"]');await state(p,'ready');await mode(p,'pending');
  await p.ev("document.querySelector('#dlgOk').focus()");await key(page,'Enter');await state(p,'pending');await p.ev("document.querySelector('#dlgOk').focus()");await key(page,' ');assert.equal(await p.ev('__d049.calls.length'),1);await focusLoop(p,page);await resolve(p,0);await state(p,'success');await mode(p,'resolve');await p.ev("document.querySelector('#dlgOk').focus()");await key(page,' ');assert.equal(await p.ev('__d049.calls.length'),2);await key(page,'Escape');await state(p,'hidden');assert.equal(await p.ev('document.activeElement.id'),'menuBtn');
  const q=await p.ev('__d049');assert.ok(q.keys.some(e=>e.key==='Enter'&&e.trusted));assert.ok(q.keys.some(e=>e.key===' '&&e.trusted));assert.equal(q.clicks.length,3);assert.ok(q.clicks.every(e=>e.trusted));same(await p.ev(SNAP),before,'keyboard copy/cancel does not alter world');
 });
 const trajectories=[];for(const interactive of [false,true])await run('RNG '+(interactive?'copy':'control'),{W:412,H:860},async(p,page)=>{const before=await p.ev(SNAP);if(interactive){await openExport(p);for(const m of ['missing','reject','resolve']){await mode(p,m);await p.tapBtn('#dlgOk');}await mode(p,'pending');await p.tapBtn('#dlgOk');await p.tapBtn('#dlgNo');await resolve(p,0,true);}else await p.tapBtn('#cityName');same(await p.ev(SNAP),before,'RNG arm initial state unchanged');const a=[await p.ev(WORLD)];for(let n=0;n<20;n++){await p.ev('__gt.simStep(1)');a.push(await p.ev(WORLD));}trajectories.push(a);});
 try{assert.equal(trajectories.length,2);assert.equal(trajectories[0].length,21);for(let d=0;d<21;d++)same(trajectories[1][d],trajectories[0][d],'full future trajectory '+d);report.rng={pass:true,days:20,snapshots:21,digest:sha(trajectories[0])};check(true,'20-day no-reload full RNG trajectory');}catch(e){check(false,'20-day no-reload full RNG trajectory',e.stack);}
 flush();
}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){let bad=0;await d049Smoke(withBrowser,(ok,n,d)=>{console.log(ok?'OK':'NG',n,d??'');if(!ok)bad++;});process.exitCode=bad?1:0;}
