// D054 native-browser acceptance. No DOM click, synthetic input or live money override.
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import { isDeepStrictEqual } from 'node:util';
import { pathToFileURL } from 'node:url';
import { ROOT,withBrowser,sleep } from './cdp.mjs';
import { pageSession } from './smoke-d011.mjs';
import { tapD053 } from './d053-capture.mjs';
import { d048KeyEvents } from './smoke-d048.mjs';
import { D054_LAYOUT } from './d054-layout-probe.mjs';
import { captureD054,loadD054,D054_UI,D054_PROBE,d054Snapshot,d054Hash,d054World,d054Persisted,d054Select,d054Hold,d054Release,d054Model,d054CompareModel } from './d054-capture.mjs';
import { D054_MODES,D054_SHOTS,D054_OPS,D054_SAVE_KEY,d054ReviewCode,d054Camera } from './d054-scenes.mjs';
import { CIVIC_TOOLS,previewOp,commitOp,undoOp,powerStatus } from '../src/sim/edit.ts';
import { stepDay } from '../src/sim/day.ts';
import { decodeLabCode,encodeLabCode } from '../src/io/labcode.ts';
const J=JSON.stringify,OUT=path.join(ROOT,'scratch/shots');
const same=(a,b,label)=>assert.ok(isDeepStrictEqual(a,b),`${label}: ${d054Hash(a)} != ${d054Hash(b)}`);
const text=(p,s)=>p.ev(`document.querySelector(${J(s)}).textContent`);
const hidden=(p,s)=>p.ev(`document.querySelector(${J(s)}).hidden`);
const tap=(p,s,mobile=true)=>tapD053(p,s,mobile);
const key=async(page,value,shift=false)=>{for(const e of d048KeyEvents(value,shift))await page.send('Input.dispatchKeyEvent',e);await sleep(80);};
const position=async(p,s,focus=false)=>{await p.ev(`(()=>{const b=document.querySelector(${J(s)});b.scrollIntoView({block:'center'});${focus?'b.focus({preventScroll:true});':''}})()`);await p.frames(2);};
const site=async(p,mobile=true)=>{await tap(p,'#siteGuide',mobile);assert.equal(await hidden(p,'#sitePanel'),false);};
const snap=d054Snapshot;
const nativeOp=async(p,page,op,mobile=true)=>{const held=await d054Hold(p,page,op,mobile);await d054Release(p,page,held.b,mobile);return held;};
async function assertClean(p,before){same(d054Persisted(await snap(p)),d054Persisted(before),'cancel preserves full observed world/save/history/storage');assert.equal(await p.ev('__gt.stroke()'),null);assert.equal(await p.ev('__gt.previewCount()'),0);assert.equal(await p.ev('__gt.ui().pointers'),0);assert.equal((await p.ev(D054_UI)).cost.hidden,true);}
async function assertModal(p){const a=await p.ev(`(()=>{const e=document.querySelector('#sitePanel'),r=e.querySelector('.card').getBoundingClientRect();return {hidden:e.hidden,role:e.getAttribute('role'),modal:e.getAttribute('aria-modal'),label:document.getElementById(e.getAttribute('aria-labelledby'))?.textContent,focus:e.contains(document.activeElement),canvas:document.querySelector('canvas').inert,dock:!!document.querySelector('#dock').closest('[inert]'),rect:[r.left,r.top,r.right,r.bottom],w:innerWidth,h:innerHeight,doc:document.documentElement.scrollWidth,buttons:[...e.querySelectorAll('button')].map(b=>{const r=b.getBoundingClientRect();return {id:b.id,w:r.width,h:r.height}}),overflow:[...e.querySelectorAll('p,h2,h3,li,button')].filter(n=>n.scrollWidth>n.clientWidth+1).map(n=>n.textContent)};})()`);assert.equal(a.hidden,false);assert.equal(a.role,'dialog');assert.equal(a.modal,'true');assert.ok(a.label&&a.focus&&a.canvas&&a.dock,J(a));assert.ok(a.rect[0]>=-.5&&a.rect[1]>=-.5&&a.rect[2]<=a.w+.5&&a.rect[3]<=a.h+.5&&a.doc<=a.w,J(a));assert.ok(a.buttons.every(b=>b.w>=44&&b.h>=44),J(a));same(a.overflow,[],'no modal content overflow');}
async function assertClosed(p){assert.equal(await hidden(p,'#sitePanel'),true);assert.equal(await p.ev("document.querySelectorAll('[inert]').length"),0);assert.equal(await p.ev("document.activeElement===document.querySelector('#siteGuide')"),true,'focus returns to retained guide');}
async function focusCycle(p,page){for(let n=0;n<4;n++)for(const reverse of [false,true]){await key(page,'Tab',reverse);assert.equal(await p.ev("document.querySelector('#sitePanel').contains(document.activeElement)"),true,'native Tab trapped');}}
function expectedPreview(s,op){const pv=previewOp(s,op);return{count:pv.count,total:pv.total,cells:pv.cells.length};}
async function cameraFor(p,op){await p.ev(`__gt.view(${(op.x0+op.x1)/2+.5},${(op.z0+op.z1)/2+.5},4.4)`);await p.frames(2);}
async function newFixture(p,mode,raw){const code=encodeLabCode(raw,{deflate:true});await loadD054(p,mode,{code});return code;}
export async function d054Smoke(browser,log){
 fs.mkdirSync(OUT,{recursive:true});const report={title:'D054 native site diagnostics acceptance',device:'Chrome CDP at360x740,412x860,1280x800; not Android hardware',qualifications:['Only saved fixture setup may supply money/resources. Original simStep advances actual simulation.','All mouse/touch/key activation uses trusted CDP input; DOM focus/scroll only positions native input.','Future trajectories cover observable RNG effects; Node guards cover full hidden RNG state.','Original/candidate pairing uses frozen successful original Chrome capture, never generated from candidate.'],fixedCapture:null,baselinePairing:null,extraShots:[],checks:[],sessions:[],passed:false};
 const write=()=>fs.writeFileSync(path.join(OUT,'D054-evidence.json'),J(report,null,2));const check=(ok,name,detail='')=>{report.checks.push({ok,name,detail});log(ok,'D054 '+name,detail);};
 try{report.fixedCapture=await captureD054({phase:'after',outDir:OUT});check(report.fixedCapture.passed&&report.fixedCapture.cases.length===D054_MODES.length&&report.fixedCapture.shots.length===D054_SHOTS.length,'six fixed native scenes and nine paired PNGs');const original=JSON.parse(fs.readFileSync(path.join(ROOT,'tools/d054-baseline.json'),'utf8'));assert.equal(original.phase,'before');assert.equal(original.passed,true);assert.equal(original.baseline.commit,'74b884fea79afad8909cea606ff8ad3ebdc7fba7');
  for(const candidate of report.fixedCapture.cases){const baseline=original.cases.find(c=>c.mode===candidate.mode);assert.ok(baseline?.passed);same(candidate.pairing,baseline.pairing,candidate.mode+' original/candidate world, history, money, code, undo, six future days');for(const shot of candidate.shots){const before=baseline.shots.find(s=>s.stage===shot.stage);assert.ok(before);same(shot.camera,before.camera,shot.mode+' full realized camera');same(shot.visual,before.visual,shot.mode+' frozen visual time');same(shot.fixture,before.fixture,shot.mode+' identical immutable fixture');same(shot.viewport,before.viewport,shot.mode+' same viewport');same(shot.worldSha256,before.worldSha256,shot.mode+' shot world unchanged');}}
  report.baselinePairing={passed:true,originalCommit:original.baseline.commit,originalHtmlSha256:original.htmlSha256,cases:report.fixedCapture.cases.length,futureDays:6,fields:['initial','preview','committed','undo','recommitted','future']};check(true,'direct original Chrome pairing incl native undo and six uninterrupted future days');
 }catch(e){check(false,'fixed capture and original pairing',String(e.stack??e));}
 write();
 const extraShot=async(p,page,name,mode)=>{
  await p.ev('__gt.setVisT(2.2);__gt.setDayFrac(0)');await p.frames(2);const filename='D054-after-'+name+'-'+p.W+'.png',bytes=Buffer.from((await page.send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false})).data,'base64');assert.ok(bytes.length>10000);assert.equal(bytes.readUInt32BE(16),p.W);assert.equal(bytes.readUInt32BE(20),p.H);fs.writeFileSync(path.join(OUT,filename),bytes);
  const state=await snap(p),stateFile='D054-after-state-'+name+'.json';fs.writeFileSync(path.join(OUT,stateFile),J(state,null,2));report.extraShots.push({filename,mode,paired:false,purpose:'Supplemental candidate-only genuine native details-panel evidence; outside frozen nine before/after comparisons',sha256:d054Hash(bytes),bytes:bytes.length,htmlSha256:d054Hash(fs.readFileSync(path.join(ROOT,'dist/index.html'))),viewport:{width:p.W,height:p.H},camera:await p.ev('__gt.cam()'),visual:{visT:2.2,dayFrac:0},stateFile,stateSha256:d054Hash(state),worldSha256:d054Hash(d054World(state)),savedCodeSha256:d054Hash(state.code),ui:await p.ev(D054_UI),inputs:await p.ev('__d054Inputs')});write();
 };
 const run=async(name,mode,opt,fn)=>{const item={name,mode,viewport:opt,passed:false};report.sessions.push(item);try{await browser({width:Math.max(960,opt.W),height:900},async({page,open})=>{const p=await pageSession(page,open,opt);item.browser=await page.send('Browser.getVersion');try{await loadD054(p,mode);await fn(p,page,item);item.passed=true;check(true,name);}catch(e){item.error=String(e.stack??e);check(false,name,item.error);try{const file='D054-failure-'+name.replace(/[^a-z0-9]+/gi,'-');fs.writeFileSync(path.join(OUT,file+'.png'),Buffer.from((await page.send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false})).data,'base64'));fs.writeFileSync(path.join(OUT,file+'.json'),J({ui:await p.ev(D054_UI),state:await snap(p),inputs:await p.ev('window.__d054Inputs??[]')},null,2));}catch(debug){item.debugError=String(debug);}}try{item.inputs=await p.ev('window.__d054Inputs??[]');item.writes=await p.ev('window.__d054Writes??[]');const all=[...(item.previousInputs??[]),...(item.inputPhases??[]).flatMap(q=>q.events),...item.inputs];assert.ok(all.some(e=>e.type==='pointerdown'||e.type==='keydown'));assert.ok(all.every(e=>e.trusted));check(true,name+' genuine input');}catch(e){check(false,name+' input evidence',String(e));}item.errors=[...page.errors];item.external=page.requests.filter(u=>!/^(http:\/\/127\.0\.0\.1:\d+\/|data:|blob:|about:)/.test(u));check(!item.errors.length&&!item.external.length,name+' zero errors/external requests',J([...item.errors,...item.external]));});}catch(e){item.error=String(e.stack??e);check(false,name+' browser',item.error);}write();};
 for(const opt of [{W:360,H:740},{W:412,H:860},{W:1280,H:800,mobile:false}])await run('layout focus and modal dismissal '+opt.W,'sewage',opt,async(p,page,item)=>{
  const mobile=opt.mobile!==false;await d054Select(p,'sewage',mobile);const before=await snap(p);
  item.layout=await p.ev(`(()=>{const q=s=>document.querySelector(s).getBoundingClientRect(),g=q('#siteGuide'),bar=q('#playBar'),c=q('#civicSub'),w=q('#civicWrap');return {guide:[g.left,g.top,g.right,g.bottom,g.width,g.height],playHeight:bar.height,segmentHeight:q('#spd').height,segmentButtonHeight:q('#spd button').height,segmentBorders:[parseFloat(getComputedStyle(document.querySelector('#spd')).borderTopWidth),parseFloat(getComputedStyle(document.querySelector('#spd')).borderBottomWidth)],civic:[c.top,c.bottom],wrap:[w.top,w.bottom],rows:new Set([...document.querySelectorAll('#civicSub button')].map(e=>Math.round(e.getBoundingClientRect().top))).size,buttons:[...document.querySelectorAll('#civicSub button')].map(e=>{const r=e.getBoundingClientRect();return[r.width,r.height,r.left,r.right,r.top,r.bottom]})}})()`);
  const baselineLayoutFile=fs.existsSync(path.join(OUT,'D054-original-layout.json'))?path.join(OUT,'D054-original-layout.json'):path.join(ROOT,'tools/d054-baseline-layout.json'),originalLayout=JSON.parse(fs.readFileSync(baselineLayoutFile,'utf8'));assert.equal(originalLayout.passed,true);assert.equal(originalLayout.htmlSha256,'0b04a77ac7672de00e01a68cc2fe90c6c7c7faaf77d7eb95abe9fc7a8c5b54cd');const original=originalLayout.cases.find(c=>c.viewport.width===opt.W&&c.viewport.height===opt.H);assert.ok(original?.passed);item.originalLayout=original.layout;item.currentLayout=await p.ev(D054_LAYOUT);same(item.currentLayout,original.layout,'native candidate equals independently measured original dock/controls/civic geometry');
  assert.equal(item.layout.segmentButtonHeight,44,'original speed control44px');same(item.layout.segmentBorders,[1,1],'original segment1px top/bottom borders');assert.equal(item.layout.segmentHeight,46,'original44px control plus2px segment border');assert.equal(item.layout.playHeight,item.layout.segmentHeight,'playbar keeps original46px segment geometry');assert.ok(item.layout.guide[4]>=44&&item.layout.guide[5]>=44);assert.equal(item.layout.rows,3,'same three civic rows');assert.equal(item.layout.wrap[1],item.layout.civic[1],'no added dock row');assert.ok(item.layout.buttons.every(b=>b[0]>=44&&b[1]>=44&&b[2]>=0&&b[3]<=opt.W+.5&&b[4]>=0&&b[5]<=opt.H+.5));assert.match(await text(p,'#siteGuide'),/污水廠/);
  const shore=await p.cell(D054_OPS.sewage.x0,D054_OPS.sewage.z0);assert.equal(await p.hit(shore),'CANVAS','360 shore map target unobscured');
  for(const how of ['button','escape','backdrop']){await site(p,mobile);await assertModal(p);await focusCycle(p,page);assert.notEqual(await p.hit(shore),'CANVAS','dialog shields map');if(how==='button')await tap(p,'#siteClose',mobile);else if(how==='escape')await key(page,'Escape');else{assert.equal(await p.hit([3,3]),'DIV#sitePanel');if(mobile)await p.tapAt([3,3]);else await p.click([3,3]);}await assertClosed(p);same(d054Persisted(await snap(p)),d054Persisted(before),'details navigation is read-only');}
  await position(p,'#siteGuide',true);await key(page,' ');await assertModal(p);assert.equal(await p.ev('__gt.sim().playing'),false,'nativeSpace does not play');await key(page,'Escape');assert.equal(await p.ev('__d054Writes.length'),0,'navigation never saves');
 });
 await run('native sewage first preview CPU6 budget','sewage',{W:412,H:860},async(p,page,item)=>{
  await d054Select(p,'sewage');const before=await snap(p),op=D054_OPS.sewage;item.previewMs=[];item.firstNativePreviewIncluded=true;item.preparation='Normal product idle preparation only; no harness-invoked warmup';await page.send('Emulation.setCPUThrottlingRate',{rate:6});
  try{for(let attempt=0;attempt<12;attempt++){const h=await d054Hold(p,page,op);assert.equal(h.preview.count,1);assert.equal(h.preview.total,500);const ms=await p.ev('__gt.timing().preview');assert.ok(Number.isFinite(ms)&&ms>=0,'real original preview timing exists');item.previewMs.push(ms);await p.touch('touchCancel',[]);await p.frames(2);assert.equal(await p.ev('__gt.stroke()'),null);}}
  finally{await page.send('Emulation.setCPUThrottlingRate',{rate:1});}
  item.maxMs=Math.max(...item.previewMs);item.limitMs=16;item.method='Every sample is a new trusted native sewage pointerdown followed by native pointercancel; first genuine sewage preview after normal product idle preparation included; no harness-invoked warmup';assert.equal(item.previewMs.length,12);same(d054Persisted(await snap(p)),d054Persisted(before),'12 canceled native previews never change world/save/history');assert.ok(item.maxMs<=16,'same original CPU6 preview16ms budget, including first genuine input: '+J(item.previewMs));
 });
 await run('hidden guide Escape restores native Space playback','sewage',{W:1280,H:800,mobile:false},async(p,page,item)=>{
  await d054Select(p,'sewage',false);const before=await snap(p);await site(p,false);await key(page,'Escape');await assertClosed(p);await key(page,'Escape');await p.frames(2);assert.equal(await p.ev('__gt.ui().tool'),null);assert.equal(await hidden(p,'#siteGuide'),true,'no selectedtool/result preserves original hidden guide');item.focusAfterEscape=await p.ev("({tag:document.activeElement.tagName,id:document.activeElement.id,hidden:!!document.activeElement.closest('[hidden],[inert]')})");assert.equal(item.focusAfterEscape.hidden,false,'focus cannot remain trapped on nowhidden guide');await key(page,' ');assert.equal(await p.ev('__gt.sim().playing'),true,'next nativeSpace still starts original playback');await key(page,' ');assert.equal(await p.ev('__gt.sim().playing'),false);const after=await snap(p),elapsed=after.sim.day-before.sim.day,m=d054Model(d054ReviewCode('sewage'));assert.ok(Number.isInteger(elapsed)&&elapsed>=0);for(let day=0;day<elapsed;day++){stepDay(m.sim);powerStatus(m.sim);}item.elapsedOriginalDays=elapsed;d054CompareModel(after,m.sim,'native playback matches original model for actual elapseddays');
 });
 await run('all tool instructions and sewage layer transitions','sewage',{W:412,H:860},async(p,page)=>{
  const before=await snap(p);for(const tool of CIVIC_TOOLS){await d054Select(p,tool.id);assert.match(await text(p,'#siteGuide'),new RegExp(tool.name));await site(p);assert.match(await text(p,'#sitePanel'),new RegExp(tool.name));assert.ok((await text(p,'#siteGuideText')).trim().length>8,tool.id+' real guide');await key(page,'Escape');assert.equal(await p.ev('__gt.pipesShown()'),['water','wpipe','sewage'].includes(tool.id));same(d054World(await snap(p)),d054World(before),tool.id+' selection remains read-only');}
  for(const tool of ['water','sewage','park','wpipe','sewage','oilwell']){await d054Select(p,tool);assert.equal(await p.ev('__gt.pipesShown()'),['water','sewage','wpipe'].includes(tool));}assert.equal(await p.ev('__d054Writes.length'),0);
 });
 for(const mode of ['mixed-pipe','low-road','low-rect'])await run('actual result survives details '+mode,mode,{W:412,H:860},async(p,page,item)=>{
  const op=D054_OPS[mode];await d054Select(p,op.tool);const before=await snap(p),m=d054Model(d054ReviewCode(mode));const h=await d054Hold(p,page,op);same(h.preview,expectedPreview(m.sim,op),'same original preview');const cost=await text(p,'#costTag');assert.match(cost,/資金|現有/);if(mode==='mixed-pipe'){assert.match(cost,/已有水管/);assert.match(cost,/陸地/);}else assert.match(cost,/不足|缺/);item.result=commitOp(m.sim,op,0);await d054Release(p,page,h.b);d054CompareModel(await snap(p),m.sim);await site(p);item.resultText=await text(p,'#siteResult');assert.match(item.resultText,/完成|實際/);assert.match(item.resultText,/未完成|略過/);if(mode==='low-road')assert.match(item.resultText,/30/);if(mode==='mixed-pipe')assert.match(item.resultText,/42/);if(mode==='low-rect')assert.match(item.resultText,/0/);if(mode==='low-road'){await position(p,'#siteResult');await extraShot(p,page,'retained-road-result-panel',mode);}await key(page,'Escape');await sleep(3300);await site(p);assert.equal(await text(p,'#siteResult'),item.resultText,'actual result has no toast expiry');await key(page,'Escape');await d054Select(p,'sewage');await site(p);assert.equal(await text(p,'#siteResult'),item.resultText,'result keeps original tool across selection');await key(page,'Escape');if(item.result.ok){undoOp(m.sim);await tap(p,'#undo');d054CompareModel(await snap(p),m.sim,'original undo');await site(p);assert.notEqual(await text(p,'#siteResult'),item.resultText,'successful undo clears stale actual result');await key(page,'Escape');}else same(d054Persisted(await snap(p)),d054Persisted(before),'rejected rect never saves or changes state');
 });
 for(const variant of ['fractional-exact','fractional-short','sandbox-zero','sandbox-negative'])await run('exact original funds '+variant,'low-road',{W:412,H:860},async(p,page,item)=>{
  const raw=structuredClone(decodeLabCode(d054ReviewCode('low-road')).save.raw),op={...D054_OPS['low-road'],x1:28};
  if(variant.startsWith('fractional')){raw.tech343={act:'',prog:{},done:['B5','C8','D4a']};raw.money=variant==='fractional-exact'?12.18375:12.18;}else{raw.df=3;raw.money=variant==='sandbox-zero'?0:-1;}
  const code=await newFixture(p,'low-road',raw),m=d054Model(code);await d054Select(p,'road');const before=await snap(p),pv=previewOp(m.sim,op),h=await d054Hold(p,page,op);same(h.preview,expectedPreview(m.sim,op),'original preview precise values');item.costText=await text(p,'#costTag');if(variant.startsWith('fractional'))assert.ok(item.costText.includes('12.18375'),'fractional cost never rounded away');if(variant==='sandbox-negative')assert.match(item.costText,/-1/);item.result=commitOp(m.sim,op,0);await d054Release(p,page,h.b);d054CompareModel(await snap(p),m.sim,'precise native original commit');if(variant==='fractional-exact'||variant==='sandbox-zero')assert.equal(item.result.placed,1);else{assert.equal(item.result.placed,0);same(d054Persisted(await snap(p)),d054Persisted(before),'unaffordable or negative sandbox does not build');}await site(p);item.resultText=await text(p,'#siteResult');assert.match(item.resultText,/完成|實際/);await key(page,'Escape');
 });
 await run('held preview refreshes actual funds across day','low-road',{W:412,H:860},async(p,page,item)=>{
  const op=D054_OPS['low-road'],m=d054Model(d054ReviewCode('low-road'));await d054Select(p,op.tool);const h=await d054Hold(p,page,op);const old=await text(p,'#costTag');assert.equal(m.sim.money,30);stepDay(m.sim);powerStatus(m.sim);await p.ev('__gt.simStep(1)');const current=await snap(p);assert.equal(current.sim.money,m.sim.money);assert.notEqual(current.sim.money,30);assert.notEqual(await text(p,'#costTag'),old,'stationary hold reflects real updated funds');same((await p.ev('__gt.stroke()')).preview,expectedPreview(m.sim,op),'held authoritative preview after day');item.result=commitOp(m.sim,op,0);await d054Release(p,page,h.b);d054CompareModel(await snap(p),m.sim,'release uses same current original model');assert.equal(item.result.placed,4,'subsidy now funds actual full road');
 });
 for(const target of ['guide','close'])for(const type of ['touch','space'])await run('retained '+target+' held across day '+type,'low-road',{W:412,H:860,mobile:type==='touch'},async(p,page,item)=>{
  const mobile=type==='touch';await d054Select(p,'road',mobile);if(target==='close')await site(p,mobile);const sel=target==='guide'?'#siteGuide':'#siteClose';await position(p,sel,true);await p.ev(`window.__held=document.querySelector(${J(sel)});window.__heldScroll=document.querySelector('#sitePanel .body').scrollTop`);const rect=await p.rectOf(sel),at=await p.center(sel),start=await p.ev('__d054Inputs.length');if(type==='touch')await p.touch('touchStart',[at]);else await page.send('Input.dispatchKeyEvent',d048KeyEvents(' ')[0]);await p.ev('__gt.simStep(1)');const state=await snap(p);same(await p.rectOf(sel),rect,'held target geometry');assert.equal(await p.ev(`__held===document.querySelector(${J(sel)})&&__held.isConnected&&document.activeElement===__held`),true,'same focused node');assert.equal(await p.ev("document.querySelector('#sitePanel .body').scrollTop===__heldScroll"),true,'same held scroll');if(type==='touch')await p.release();else await page.send('Input.dispatchKeyEvent',d048KeyEvents(' ').at(-1));await p.frames(3);item.release=await p.ev(`__d054Inputs.slice(${start})`);assert.equal(item.release.filter(e=>e.type==='click'&&e.id===sel.slice(1)&&e.trusted).length,1,'exactly one genuine activation');if(target==='guide'){await assertModal(p);assert.match(await text(p,'#sitePanel'),/151/);await key(page,'Escape');}else await assertClosed(p);same(d054World(await snap(p)),d054World(state),'native callback cannot alter current model');assert.equal(await p.ev('__gt.sim().playing'),false);
 });
 await run('details captures held area and cancels map gesture','mixed-pipe',{W:360,H:740},async(p,page)=>{
  await d054Select(p,'wpipe');const before=await snap(p),op=D054_OPS['mixed-pipe'];await d054Hold(p,page,op);await position(p,'#siteGuide',true);await key(page,'Enter');await assertModal(p);assert.equal(await p.ev('__gt.stroke()'),null);assert.match(await text(p,'#siteEstimate'),/已有水管/);assert.match(await text(p,'#siteEstimate'),/陸地/);await p.release();same(d054Persisted(await snap(p)),d054Persisted(before),'opening details never commits held stroke');await key(page,'Escape');await assertClean(p,before);
 });
 for(const interruption of ['Escape','tool','details','resize','second-finger','cancel'])await run('native interruption '+interruption,'low-road',{W:412,H:860},async(p,page)=>{
  await d054Select(p,'road');const before=await snap(p),h=await d054Hold(p,page,D054_OPS['low-road']);
  if(interruption==='Escape')await key(page,'Escape');
  if(interruption==='tool'){await position(p,'.tool[data-t="plant"]',true);await key(page,'Enter');}
  if(interruption==='details'){await position(p,'#siteGuide',true);await key(page,'Enter');await assertModal(p);}
  if(interruption==='resize'){await page.send('Emulation.setDeviceMetricsOverride',{width:360,height:740,deviceScaleFactor:1,mobile:true});await p.frames(3);}
  if(interruption==='second-finger'){const other=await p.center('#siteGuide');await p.touch('touchStart',[[...h.b,0],[...other,1]]);await p.frames(2);await p.touch('touchEnd',[[...other,1]]);}
  if(interruption==='cancel')await p.touch('touchCancel',[]);
  assert.equal(await p.ev('__gt.stroke()'),null);if(interruption!=='cancel')await p.release();if(!await hidden(p,'#sitePanel'))await key(page,'Escape');await assertClean(p,before);
 });
 await run('second finger cancels held details close','mixed-pipe',{W:412,H:860},async(p,page)=>{
  await d054Select(p,'wpipe');const before=await snap(p);await site(p);const at=await p.center('#siteClose');await p.touch('touchStart',[[...at,0]]);await p.touch('touchStart',[[...at,0],[80,120,1]]);await p.touch('touchEnd',[[80,120,1]]);await p.release();if(!await hidden(p,'#sitePanel'))await key(page,'Escape');assert.equal(await p.ev("document.querySelectorAll('[inert]').length"),0,'second pointer leaves no modal lock');await assertClean(p,before);
 });
 await run('native blur abandons held gesture','low-road',{W:1280,H:800,mobile:false},async(p,page,item)=>{
  await d054Select(p,'road',false);await page.send('Page.bringToFront');await p.ev("window.__d054WindowBlur=[];addEventListener('blur',e=>{if(e.target===window)__d054WindowBlur.push({trusted:e.isTrusted,windowTarget:true,focused:document.hasFocus(),visibility:document.visibilityState})})");
  const before=await snap(p),h=await d054Hold(p,page,D054_OPS['low-road'],false);item.focusBefore=await p.ev('document.hasFocus()');assert.equal(item.focusBefore,true,'original page must really be focused before losing focus');let other=null;
  try{other=(await page.send('Target.createTarget',{url:'about:blank'})).targetId;const session=(await page.send('Target.attachToTarget',{targetId:other,flatten:false})).sessionId;
   // Page.bringToFront explicitly activates AND focuses WebContents (Chromium
   // content/browser/devtools/protocol/page_handler.cc). A separate headless
   // window Target.activateTarget alone did not generate any WINDOW blur.
   await page.send('Target.sendMessageToTarget',{sessionId:session,message:J({id:1,method:'Page.bringToFront'})});await sleep(150);item.windowBlurObserved=await p.waitFor(async()=>await p.ev('__d054WindowBlur.length>0'),2000);await page.send('Page.bringToFront');await p.frames(2);item.blur=await p.ev('__d054WindowBlur');assert.ok(item.windowBlurObserved&&item.blur.every(e=>e.trusted&&e.windowTarget),'genuine WINDOW blur required, never descendant button blur');assert.equal(await p.ev('__gt.stroke()'),null);await d054Release(p,page,h.b,false);await assertClean(p,before);
  }finally{await page.send('Page.bringToFront');if(other)await page.send('Target.closeTarget',{targetId:other});}
 });
 await run('pagehide closes details and releases inert','sewage',{W:412,H:860},async(p,page,item)=>{
  await d054Select(p,'sewage');await site(p);await p.ev("addEventListener('pagehide',e=>sessionStorage.setItem('D054-pagehide',JSON.stringify({trusted:e.isTrusted,inert:document.querySelectorAll('[inert]').length,hidden:document.querySelector('#sitePanel').hidden,stroke:__gt.stroke()})))");const before=await snap(p);const inputs=await p.ev('__d054Inputs');await p.open('');await p.ev(D054_PROBE);item.previousInputs=inputs;item.pagehide=await p.ev("JSON.parse(sessionStorage.getItem('D054-pagehide'))");same(item.pagehide,{trusted:true,inert:0,hidden:true,stroke:null},'real navigation pagehide cleanup');assert.equal(await p.ev("document.querySelectorAll('[inert]').length"),0);const loaded=await snap(p);assert.equal(loaded.sim.money,before.sim.money);same(loaded.history,before.history,'reload history');await d054Select(p,'sewage');await site(p);await key(page,'Escape');
 });
 await run('cross-surface old mouse release never builds','low-road',{W:1280,H:800,mobile:false},async(p,page)=>{
  await d054Select(p,'road',false);const before=await snap(p);const h=await d054Hold(p,page,D054_OPS['low-road'],false);await position(p,'#siteGuide',true);await key(page,'Enter');await assertModal(p);await d054Release(p,page,h.b,false);same(d054Persisted(await snap(p)),d054Persisted(before),'old map release into details is inert');
  const close=await p.center('#siteClose');await page.send('Input.dispatchMouseEvent',{type:'mousePressed',x:close[0],y:close[1],button:'left',buttons:1,clickCount:1});await key(page,'Escape');await page.send('Input.dispatchMouseEvent',{type:'mouseMoved',x:h.a[0],y:h.a[1],button:'left',buttons:1});await page.send('Input.dispatchMouseEvent',{type:'mouseReleased',x:h.a[0],y:h.a[1],button:'left',buttons:0,clickCount:1});await p.frames(3);await assertClean(p,before);
  await nativeOp(p,page,D054_OPS['low-road'],false);assert.equal((await snap(p)).sim.money,0,'fresh next genuine stroke still works');
 });
 await run('resource fresh partial exhausted wrong and gas distinction','depleted-oil',{W:412,H:860},async(p,page,item)=>{
  item.resources=[];item.inputPhases=[];const siteOp=D054_OPS['depleted-oil'];for(const consumed of [0,120,240]){const raw=structuredClone(decodeLabCode(d054ReviewCode('depleted-oil')).save.raw);raw.bl=raw.bl.filter(b=>b[0]!==siteOp.z0*72+siteOp.x0);raw.rdep=consumed?[[siteOp.z0*72+siteOp.x0,consumed]]:null;await newFixture(p,'depleted-oil',raw);await d054Select(p,'oilwell');const before=await snap(p);await d054Hold(p,page,siteOp);const cost=await text(p,'#costTag');assert.ok(cost.includes(String(240-consumed)),cost);if(consumed===240)assert.match(cost,/可建.*不再產出|仍能建.*不再產出/);await p.touch('touchCancel',[]);await assertClean(p,before);item.resources.push({consumed,cost});if(consumed===240){await site(p);await position(p,'#siteEstimate');await extraShot(p,page,'depleted-oil-guide-panel','depleted-oil');await key(page,'Escape');same(d054Persisted(await snap(p)),d054Persisted(before),'resource details is read-only');await d054Select(p,'gaswell');await d054Hold(p,page,{...siteOp,tool:'gaswell'});assert.doesNotMatch(await text(p,'#costTag'),/不再產出|耗盡|枯竭/);await p.touch('touchCancel',[]);await assertClean(p,before);await d054Select(p,'mine');await d054Hold(p,page,{...siteOp,tool:'mine'});assert.match(await text(p,'#costTag'),/需礦藏資源格/);await p.touch('touchCancel',[]);await assertClean(p,before);}item.inputPhases.push({consumed,events:await p.ev('__d054Inputs')});}
 });
 await run('native grouped 3x3 demolition and undo','low-rect',{W:412,H:860},async(p,page,item)=>{
  const raw=structuredClone(decodeLabCode(d054ReviewCode('low-rect')).save.raw);raw.money=10000;const code=await newFixture(p,'low-rect',raw),m=d054Model(code),build={tool:'megaproject',k:'tap',x0:28,z0:26,x1:28,z1:26},doze={tool:'doze',k:'rect',x0:28,z0:26,x1:30,z1:28};await cameraFor(p,doze);await d054Select(p,'megaproject');const held=await d054Hold(p,page,build);assert.deepEqual(held.preview,{count:1,total:4500,cells:9});item.built=commitOp(m.sim,build,0);await d054Release(p,page,held.b);const built=await snap(p);d054CompareModel(built,m.sim,'native full3x3build');await d054Select(p,'doze');const original=previewOp(m.sim,doze),h=await d054Hold(p,page,doze);same(h.preview,{count:original.count,total:original.total,cells:original.cells.length},'original all9eligible demolition preview');assert.equal(original.count,9);assert.equal(original.total,18);item.demolition=commitOp(m.sim,doze,0);assert.equal(item.demolition.placed,1);assert.equal(item.demolition.spent,2);await d054Release(p,page,h.b);const removed=await snap(p);d054CompareModel(removed,m.sim,'one original grouped removal');for(let z=26;z<=28;z++)for(let x=28;x<=30;x++)assert.equal(removed.layers.occ[z*72+x],0,'all9footprintcells cleared');await site(p);item.resultText=await text(p,'#siteResult');assert.match(item.resultText,/拆除|完成/);assert.match(item.resultText,/\$2/);assert.doesNotMatch(item.resultText,/未完成\s*8|8\s*(格|項)?未完成/,'one grouped removal cannot fabricate8unfinishedcells');await key(page,'Escape');undoOp(m.sim);await tap(p,'#undo');const restored=await snap(p);d054CompareModel(restored,m.sim,'native undo restores original full3x3');same(restored.layers.occ,built.layers.occ,'all9samebuilding restored');assert.equal(restored.sim.money,built.sim.money);same(restored.layers.zone,built.layers.zone,'undo restores underlying zones');
 });
 await run('native level2 demolition confirmation expiration','low-rect',{W:412,H:860},async(p,page,item)=>{
  const raw=structuredClone(decodeLabCode(d054ReviewCode('low-rect')).save.raw),i=26*72+28;raw.money=10000;raw.bl.push([i,1,2,0,20,0,3,1]);const code=await newFixture(p,'low-rect',raw),m=d054Model(code),op={tool:'doze',k:'rect',x0:28,z0:26,x1:28,z1:26};await d054Select(p,'doze');const before=await snap(p);let h=await d054Hold(p,page,op);item.first=commitOp(m.sim,op,0);await d054Release(p,page,h.b);assert.equal(item.first.armed,true);d054CompareModel(await snap(p),m.sim,'first native tap only arms');await site(p);assert.match(await text(p,'#siteResult'),/3\s*秒/,'persistent arm result explains original3second condition');await key(page,'Escape');await sleep(3100);h=await d054Hold(p,page,op);item.expired=commitOp(m.sim,op,5000);await d054Release(p,page,h.b);assert.equal(item.expired.armed,true);const rearmed=await snap(p);d054CompareModel(rearmed,m.sim,'expired second tap only rearms');assert.equal(rearmed.sim.money,before.sim.money);same(rearmed.layers.occ,before.layers.occ,'expired confirmation cannot demolish');h=await d054Hold(p,page,op);item.confirmed=commitOp(m.sim,op,5500);await d054Release(p,page,h.b);assert.equal(item.confirmed.placed,1);assert.equal(item.confirmed.spent,2);d054CompareModel(await snap(p),m.sim,'third native tap genuinely confirms withinwindow');await site(p);assert.match(await text(p,'#siteResult'),/完成/);await key(page,'Escape');
 });
 const trajectories=[];for(const navigated of [false,true])await run('paired navigation future '+navigated,'mixed-pipe',{W:412,H:860},async(p,page,item)=>{
  if(navigated){for(const id of ['wpipe','oilwell','mine','gaswell','sewage','megaproject']){await d054Select(p,id);await site(p);await key(page,'Escape');}}else{await tap(p,'#menuBtn');await key(page,'Escape');}const states=[d054World(await snap(p))];for(let day=0;day<6;day++){await p.ev('__gt.simStep(1)');states.push(d054World(await snap(p)));}item.trajectory={snapshots:states.length,sha256:d054Hash(states)};trajectories.push(states);
 });
 try{assert.equal(trajectories.length,2);same(trajectories[0],trajectories[1],'six uninterrupted original sim days navigation/control');check(true,'navigation leaves future full exposed stochastic trajectory unchanged');}catch(e){check(false,'navigation future pairing',String(e.stack??e));}
 report.passed=report.checks.every(c=>c.ok);write();return report;
}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){let failed=0;await d054Smoke(withBrowser,(ok,n,d)=>{console.log(ok?'OK':'NG',n,d??'');if(!ok)failed++;});process.exitCode=failed?1:0;}
