// D050 genuine Chrome/CDP touch, keyboard and Input.insertText. No OS clipboard read.
// Confirmation decisions and pagehide/pageshow are explicit test injections.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {isDeepStrictEqual} from 'node:util';import {pathToFileURL} from 'node:url';
import {ROOT,withBrowser,sleep} from './cdp.mjs';import {pageSession,grew} from './smoke-d011.mjs';import {d048KeyEvents} from './smoke-d048.mjs';import {decodeLabCode} from '../src/io/labcode.ts';
import {D048_CAMERA,D048_BASELINE_CAMERA,D048_SAVE_KEY,D048_VIEWS,d048ReviewCode,d048FixtureManifest} from './d048-scenes.mjs';
const J=JSON.stringify,OUT=path.join(ROOT,'scratch/shots'),hash=x=>createHash('sha256').update(typeof x==='string'||Buffer.isBuffer(x)?x:J(x)).digest('hex');
const same=(a,b,why)=>assert.ok(isDeepStrictEqual(a,b),`${why}: ${hash(a)} != ${hash(b)}`),FIXTURE=d048ReviewCode();
const SNAP=`({sim:__gt.sim(),layers:__gt.layers(),buildings:__gt.buildingList(),history:__gt.history(),commission:__gt.simCms(),code:__gt.save(),saved:__gt.saved(),lastDay:__gt.lastDay(),dayReport:__gt.dayRep(),url:location.href,historyLength:history.length,storage:Object.fromEntries(Object.keys(localStorage).sort().map(k=>[k,localStorage.getItem(k)]))})`;
const WORLD=`({sim:__gt.sim(),layers:__gt.layers(),buildings:__gt.buildingList(),history:__gt.history(),commission:__gt.simCms(),code:__gt.save(),lastDay:__gt.lastDay(),dayReport:__gt.dayRep()})`;
const FIELD=`(()=>{const t=document.querySelector('#dlg textarea'),e=document.querySelector('#dlg .err');return {value:t.value,error:e.textContent,invalid:t.getAttribute('aria-invalid'),describedBy:t.getAttribute('aria-describedby'),errorId:e.id,errorRole:e.getAttribute('role')};})()`;
const PROBE=`window.__d050={pointers:[],inputs:[],submits:[],keys:[],confirms:[]};addEventListener('pointerdown',e=>__d050.pointers.push({type:e.pointerType,trusted:e.isTrusted}),true);for(const type of ['beforeinput','input'])addEventListener(type,e=>{if(e.target.matches('#dlg textarea'))__d050.inputs.push({type,trusted:e.isTrusted,inputType:e.inputType,data:e.data,value:e.target.value})},true);addEventListener('click',e=>{if(e.target.closest('#dlgOk'))__d050.submits.push({trusted:e.isTrusted,value:document.querySelector('#dlg textarea').value})},true);addEventListener('keydown',e=>__d050.keys.push({key:e.key,trusted:e.isTrusted}),true);`;
async function key(page,k,shift=false){for(const e of d048KeyEvents(k,shift))await page.send('Input.dispatchKeyEvent',e);await sleep(70);}
async function selectAll(page){for(const e of [{type:'rawKeyDown',key:'Control',code:'ControlLeft',windowsVirtualKeyCode:17,modifiers:2},{type:'rawKeyDown',key:'a',code:'KeyA',windowsVirtualKeyCode:65,modifiers:2},{type:'keyUp',key:'a',code:'KeyA',windowsVirtualKeyCode:65,modifiers:2},{type:'keyUp',key:'Control',code:'ControlLeft',windowsVirtualKeyCode:17,modifiers:0}])await page.send('Input.dispatchKeyEvent',e);}
async function replace(p,page,text,mobile=true){if(mobile)await p.tapBtn('#dlg textarea');else await p.clickBtn('#dlg textarea');await selectAll(page);const count=await p.ev('__d050.inputs.length');if(text){await page.send('Input.insertText',{text});}else{for(const type of ['rawKeyDown','keyUp'])await page.send('Input.dispatchKeyEvent',{type,key:'Backspace',code:'Backspace',windowsVirtualKeyCode:8});}await p.frames(2);const field=await p.ev(FIELD);assert.equal(field.value,text,'exact original input bytes, no normalization');const events=await p.ev(`__d050.inputs.slice(${count})`);assert.ok(events.some(e=>e.type==='input'&&e.trusted),'actual trusted input must occur');assert.ok(events.every(e=>e.trusted));return field;}
async function load(p){await p.open('sample=seed516&clean=1');await p.ev(`__gt.clearSave();localStorage.setItem(${J(D048_SAVE_KEY)},${J(FIXTURE)})`);await p.open('');await p.ev(`__gt.view(${D048_CAMERA.x},${D048_CAMERA.z},${D048_CAMERA.zoom});__gt.setVisT(2.2);__gt.setDayFrac(0)`);await p.ev('__gt.saveNow()');await p.ev('__gt.journalFlush()');await p.ev('__gt.saveNow()');assert.ok(await p.waitFor(async()=>!(await p.toasts()).length,5000));same(await p.ev('__gt.cam()'),D048_BASELINE_CAMERA,'fixed baseline camera');await p.ev(PROBE);}
async function open(p,kind='paste',mobile=true){const tap=mobile?p.tapBtn:p.clickBtn;assert.ok(await tap('#menuBtn'));assert.ok(await tap(`#menu [data-m="${kind}"]`));assert.equal(await p.ev("document.querySelector('#dlg').hidden"),false);await clean(p);}
async function clean(p){const f=await p.ev(FIELD);assert.equal(f.error,'');assert.equal(f.invalid,null);assert.equal(f.describedBy,'dlgSub dlgError');assert.equal(f.errorId,'dlgError');assert.equal(f.errorRole,'alert');return f;}
async function invalid(p,code,mobile=true){const before=await p.ev('__d050.submits.length');assert.ok(await (mobile?p.tapBtn:p.clickBtn)('#dlgOk'));const r=decodeLabCode(code);assert.equal(r.ok,false);const f=await p.ev(FIELD);assert.equal(f.value,code);assert.equal(f.error,r.error);assert.equal(f.invalid,'true');assert.equal(f.errorId,'dlgError');assert.equal(f.describedBy,'dlgSub dlgError');same(await p.ev(`__d050.submits.slice(${before})`),[{trusted:true,value:code}],'each invalid submit is actually clicked once');assert.equal(await p.ev("getComputedStyle(document.querySelector('#dlg textarea')).borderTopColor"),'rgb(255, 154, 154)');return f;}
async function layout(p){const s=await p.ev(`(()=>{const card=document.querySelector('#dlg .card');return {overflow:document.documentElement.scrollWidth>innerWidth||card.scrollWidth>card.clientWidth+1,rects:['#dlg .err','#dlgOk','#dlgNo'].map(sel=>{const e=document.querySelector(sel),r=e.getBoundingClientRect();return {sel,w:r.width,h:r.height,l:r.left,r:r.right,t:r.top,b:r.bottom};})};})()`);assert.equal(s.overflow,false);for(const r of s.rects){assert.ok(r.l>=0&&r.r<=p.W+.5&&r.t>=0&&r.b<=p.H+.5,J(r));if(r.sel!=='#dlg .err')assert.ok(r.w>=44&&r.h>=44,J(r));}return s;}
async function focusLoop(p,page){for(const shift of [false,true])for(let i=0;i<5;i++){await key(page,'Tab',shift);assert.equal(await p.ev("document.querySelector('#dlg').contains(document.activeElement)&&!document.activeElement.closest('[hidden],[inert]')"),true);}}
export async function d050Smoke(browser,log){fs.mkdirSync(OUT,{recursive:true});const {baseline:oldBaseline,faultInjection:oldFaults,...fixture}=d048FixtureManifest();const report={base:'71bf40db307663c2713ec6a83c2aa4c327e5c7ca',candidateHtmlSha256:hash(fs.readFileSync(path.join(ROOT,'dist/index.html'))),fixture:{...fixture,baseline:{commit:'71bf40db307663c2713ec6a83c2aa4c327e5c7ca',htmlSha256:'68d825da457c2f64dec5b72da04fbda0dac131fbe8ff9f00b785f1a21f6bb000',captureRun:37550379693}},mode:'Chrome/CDP touch simulation and trusted Input.insertText; not Android hardware or native OS clipboard paste',injections:'Confirm decisions and pagehide/pageshow events only. No storage faults or clipboard reads in D050.',checks:[],sessions:[],shots:[]};
 const check=(ok,name,detail)=>{report.checks.push({ok,name,detail});log(ok,'D050 '+name,detail);},flush=()=>fs.writeFileSync(path.join(OUT,'D050-evidence.json'),J(report,null,2)+'\n');
 const run=async(name,opt,fn)=>{try{await browser({width:Math.max(opt.W,960),height:900},async({open:openPage,page})=>{const p=await pageSession(page,openPage,opt);await load(p);const shot=async(label)=>{await p.frames(3);await layout(p);same(await p.ev('__gt.cam()'),D048_BASELINE_CAMERA,'shot camera');const bytes=Buffer.from((await page.send('Page.captureScreenshot',{format:'png'})).data,'base64'),file=`D050-${label}-${p.W}x${p.H}.png`;fs.writeFileSync(path.join(OUT,file),bytes);report.shots.push({file,sha256:hash(bytes),width:p.W,height:p.H,field:await p.ev(FIELD),camera:await p.ev('__gt.cam()'),simulatedAndroid:true});};try{await fn(p,page,shot);check(true,name);}catch(e){check(false,name,e.stack);}await page.send('Runtime.evaluate',{expression:'0',returnByValue:true});const q=await p.ev('__d050'),external=page.requests.filter(u=>!/^(http:\/\/127\.0\.0\.1:\d+\/|data:|blob:|about:)/.test(u));check(page.errors.length===0&&external.length===0,name+' zero console errors / external requests',[...page.errors,...external].join('\n'));const trusted=opt.mobile===false?q.keys.length>0&&q.keys.every(e=>e.trusted):q.pointers.length>0&&q.pointers.every(e=>e.trusted&&e.type==='touch');check(trusted&&q.inputs.every(e=>e.trusted),name+' trusted input',J({pointers:q.pointers.length,inputs:q.inputs.length,keys:q.keys.length}));report.sessions.push({name,probe:q,errors:[...page.errors],external});});}catch(e){check(false,name+' browser',e.stack);}flush();};
 for(const {width:W,height:H}of D048_VIEWS)await run('portrait '+W,{W,H},async(p,page,shot)=>{
  const before=await p.ev(SNAP),journal=await p.ev('__gt.journalRows()');await open(p);
  if(W===360){await invalid(p,'');await p.tapBtn('#dlg textarea');const at=await p.ev('__d050.inputs.length');await page.send('Input.insertText',{text:FIXTURE});await p.frames(3);const f=await clean(p);assert.equal(f.value,FIXTURE);same(await p.ev('__d050.submits'),[{trusted:true,value:''}],'exact baseline flow: no second submit');assert.ok((await p.ev(`__d050.inputs.slice(${at})`)).every(e=>e.trusted&&e.inputType==='insertText'));await shot('edited-empty-error-after');}
  else{await p.tapBtn('#dlg textarea');await page.send('Input.insertText',{text:'!!!'});await invalid(p,'!!!');await shot('invalid-error-after');await replace(p,page,'!!!');assert.equal((await p.ev(FIELD)).invalid,'true','replacing with identical rejected bytes retains the still-current error');assert.equal((await p.ev(FIELD)).error,decodeLabCode('!!!').error);}
  const longVersion=Buffer.from(J({v:'<b>不支援</b>'+('較新的分享碼版本'.repeat(7))})).toString('base64');
  for(const code of ['???','e30=',Buffer.from('{').toString('base64'),longVersion]){await replace(p,page,code);await clean(p);await invalid(p,code);await invalid(p,code);await layout(p);assert.equal(await p.ev("document.querySelector('#dlg .err b')===null"),true,'error text must not become HTML');if(W===412&&code===longVersion)await shot('retry-new-error-after');}
  await replace(p,page,FIXTURE);await clean(p);same(await p.ev(SNAP),before,'editing valid code does not import');same(await p.ev('__gt.journalRows()'),journal,'invalid/edit attempts do not append journal');
  await focusLoop(p,page);await p.tapBtn('#dlgNo');same(await p.ev(SNAP),before,'cancel unchanged');await open(p);assert.equal((await clean(p)).value,'');if(W===360)await shot('reopened-after');await p.tapBtn('#dlgNo');
  for(const how of ['escape','backdrop','pagehide']){await open(p);await invalid(p,'');if(how==='escape')await key(page,'Escape');else if(how==='backdrop')await p.tapAt([4,4]);else await p.ev("dispatchEvent(new PageTransitionEvent('pagehide',{persisted:true}));dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true}))");assert.equal(await p.ev("document.querySelector('#dlg').hidden"),true);await clean(p);await open(p,'export');assert.equal(await p.ev("document.querySelector('#copyStatus').dataset.phase"),'ready');await clean(p);await p.tapBtn('#dlgNo');same(await p.ev(SNAP),before,'dismissal/export unchanged '+how);}
 });
 await run('native keyboard and deleting a rejected value',{W:1280,H:800,mobile:false},async(p,page)=>{const before=await p.ev(SNAP);await open(p,'paste',false);await p.ev("document.querySelector('#dlgOk').focus()");await key(page,'Enter');assert.equal((await p.ev(FIELD)).error,'分享碼是空的');assert.equal((await p.ev(FIELD)).invalid,'true');await replace(p,page,'!!!',false);await clean(p);await p.ev("document.querySelector('#dlgOk').focus()");await key(page,' ');assert.equal((await p.ev(FIELD)).invalid,'true');await replace(p,page,'',false);await clean(p);assert.ok((await p.ev('__d050.inputs')).some(e=>e.inputType==='deleteContentBackward'&&e.trusted));await focusLoop(p,page);await key(page,'Escape');assert.equal(await p.ev('document.activeElement.id'),'menuBtn');await clean(p);same(await p.ev(SNAP),before,'keyboard invalid/edit/cancel is read-only');});
 await run('accepted own/view-only imports and overwrite decline',{W:412,H:860},async(p,page)=>{const before=await p.ev(SNAP),journal=await p.ev('__gt.journalRows()'),own=before.code;assert.ok(decodeLabCode(own).save.raw.d3);await open(p);await replace(p,page,own);await p.ev("window.confirm=m=>{__d050.confirms.push({message:m,accepted:false});return false}");await p.tapBtn('#dlgOk');assert.equal(await p.ev('__d050.confirms.length'),1);assert.equal(await p.ev("document.querySelector('#dlg').hidden"),false);assert.equal((await clean(p)).value,own);same(await p.ev(SNAP),before,'declined overwrite never saves or loads');same(await p.ev('__gt.journalRows()'),journal,'declined overwrite journal unchanged');await p.ev("window.confirm=m=>{__d050.confirms.push({message:m,accepted:true});return true}");await p.tapBtn('#dlgOk');assert.equal(await p.ev('__d050.confirms.length'),2);assert.equal(await p.ev("document.querySelector('#dlg').hidden"),true);await clean(p);const live=await p.ev('__gt.sim()');assert.equal(live.day,before.sim.day);assert.equal(live.money,before.sim.money);assert.equal((await p.ev('__gt.simCms()')).acc,12.5);assert.ok(grew(before.history,await p.ev('__gt.history()'),await p.ev('__gt.restyled()')).ok);const parsed=decodeLabCode(await p.ev('__gt.save()'));assert.ok(parsed.ok&&parsed.save.raw.d3);assert.equal(parsed.save.raw.cms385.acc,12);assert.equal(parsed.save.raw.cms3d.acc,12.5);await p.ev('__gt.journalFlush()');await p.ev('__gt.saveNow()');assert.ok(await p.waitFor(async()=>!(await p.toasts()).length,5000));await open(p);await replace(p,page,FIXTURE);await p.tapBtn('#dlgOk');assert.equal(await p.ev('__d050.confirms.length'),2,'view-only code never requests overwrite');assert.equal(await p.ev('__gt.sim()'),null);assert.equal(await p.ev('__gt.save()'),null,'playable-only debug exporter is intentionally unavailable');assert.ok(await p.ev('__gt.saved()'));await clean(p);await open(p,'export');const viewCode=await p.ev("document.querySelector('#dlg textarea').value"),viewParsed=decodeLabCode(viewCode);assert.ok(viewParsed.ok);assert.equal(viewParsed.save.raw.d3,undefined);assert.equal(viewParsed.save.day,150);await p.tapBtn('#dlgNo');await clean(p);});
 const trajectories=[];for(const interactive of [false,true])await run('RNG '+(interactive?'retry':'control'),{W:412,H:860},async(p,page)=>{const before=await p.ev(SNAP);if(interactive){await open(p);await invalid(p,'');await replace(p,page,'!!!');await invalid(p,'!!!');await replace(p,page,FIXTURE);await clean(p);await p.tapBtn('#dlgNo');}else await p.tapBtn('#cityName');same(await p.ev(SNAP),before,'RNG arm unchanged before stepping');const states=[await p.ev(WORLD)];for(let i=0;i<20;i++){await p.ev('__gt.simStep(1)');states.push(await p.ev(WORLD));}trajectories.push(states);});
 try{assert.equal(trajectories.length,2);assert.equal(trajectories[0].length,21);for(let i=0;i<21;i++)same(trajectories[0][i],trajectories[1][i],'full future trajectory '+i);report.rng={pass:true,days:20,snapshots:21,digest:hash(trajectories[0])};check(true,'20-day no-reload matched full trajectory');}catch(e){check(false,'20-day no-reload matched full trajectory',e.stack);}flush();
}
export function d050CopyImageGuard(log){const expected={'D049-unsupported-after-360x740.png':'4b0c45dcc824afdde0b3082cdb81e687674b442eda2ede8d317a1462fb006121','D049-rejected-after-360x740.png':'5561ec25fe9d81ef7dccc16dd3b40f4f84d1fa5e4ce790930eef3b4bc86a79b2','D049-ready-after-412x860.png':'d7cbe8a5c3935d9a8a6d8baa2c1389bef7c59b553619842d49d58e6c7e3912d1','D049-success-after-412x860.png':'609128dd9fd797dd5479a810f63fc0e29bc89aa596dfcd5eef9f54fda83e0884','D049-pending-after-412x860.png':'c8cd6ae9af6313822b9599c738ca5bd2ad41bc651edf4b29d88a26c27b61e76a','D049-reopened-after-412x860.png':'d7cbe8a5c3935d9a8a6d8baa2c1389bef7c59b553619842d49d58e6c7e3912d1'};try{for(const [f,sha]of Object.entries(expected))assert.equal(hash(fs.readFileSync(path.join(OUT,f))),sha,f);log(true,'D050: all six D049 copy-dialog PNGs remain byte-identical');}catch(e){log(false,'D050: D049 copy-dialog PNG regression',e.stack);}}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){let bad=0;await d050Smoke(withBrowser,(ok,n,d)=>{console.log(ok?'OK':'NG',n,d??'');if(!ok)bad++;});console.log('D050 standalone only; complete aggregate also runs unchanged D049 PNG guard');process.exitCode=bad?1:0;}
