import{d057RenderBudget}from'./d057-render-budget.mjs';import{D057_REQUIRED_COLORS}from'./d057-palette.mjs';
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import * as THREE from 'three';import{pathToFileURL}from'node:url';
import{ROOT}from'./cdp.mjs';import{drawOne,kindHashes}from'./d018-kinds.mjs';import{kindTableFrom}from'../src/content/kindTable.ts';import{drawKind}from'../src/render/kindArt.ts';
import{BRITISH_HERITAGE,BRITISH_HERITAGE_KINDS}from'../src/content/britishHeritage.ts';import{BRITISH_CIVIC}from'../src/content/britishCivic.ts';import{D057_LEGACY}from'./d057-legacy.mjs';import{assertD057Scope}from'./d057-scope.mjs';
const read=f=>JSON.parse(fs.readFileSync(path.join(ROOT,f),'utf8'));
function opening(r,u,y){const ray=new THREE.Raycaster(new THREE.Vector3(u,y*r.H,.9),new THREE.Vector3(0,0,-1),0,.7);return r.G.every(g=>{const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(g.pos,3));const m=new THREE.MeshBasicMaterial({side:THREE.DoubleSide}),mesh=new THREE.Mesh(geo,m);mesh.updateMatrixWorld();const empty=ray.intersectObject(mesh).length===0;geo.dispose();m.dispose();return empty;});}
export async function d057Guards(log){let failures=0;const test=(n,f)=>{try{f();log(true,'D057 '+n)}catch(e){failures++;log(false,'D057 '+n,e.stack)}};
 const before=read('fixtures/d057-kinds-before.json'),now=kindHashes(),gold=read('fixtures/d057-current-art.json'),KT=kindTableFrom(read('src/content/lab-kinds.json')),looks=read('src/content/lab-looks.json').looks;
 test('eight named existing exteriors; three native tools and five imported-city kinds',()=>{assert.equal(BRITISH_HERITAGE.length,8);assert.equal(BRITISH_HERITAGE.filter(x=>x.native).length,3);assert.equal(new Set(BRITISH_HERITAGE.map(x=>x.name)).size,8);for(const b of BRITISH_HERITAGE)assert.ok(!BRITISH_CIVIC.some(x=>x.k===b.k));});
 test('reference-derived palettes are present in all eight actual geometries',()=>{for(const{k}of BRITISH_HERITAGE){const r=drawOne(KT,looks,k,1,0,KT.size(k));for(const c of D057_REQUIRED_COLORS[k])assert.ok(r.used.includes(c),k+' '+c);}});
 test('exact sample render deltas include real shadow submissions and preserve prior baseline budgets',()=>{assert.deepEqual(d057RenderBudget(),read('fixtures/d057-render-budget.json'));});
 test('175 untouched kinds × nine variants, including all eleven D056 buildings, remain exact',()=>{assert.equal(before.commit,'3330f0485cf8e37a40917f04ba16f7fa2d432639');assert.deepEqual(kindHashes(D057_LEGACY),before.kinds);assert.deepEqual(Object.keys(now),Object.keys(before.kinds));for(const k in now)if(!BRITISH_HERITAGE_KINDS.has(+k))assert.deepEqual(now[k],before.kinds[k],k);else for(let v=0;v<9;v++)assert.notEqual(now[k].h[v],before.kinds[k].h[v]);});
 test('all eight current geometries exactly pinned; independent position/color mutations rejected',()=>{for(const{k}of BRITISH_HERITAGE)assert.deepEqual(now[k],gold.kinds[k]);for(const field of['pos','col']){const changed=kindHashes({},(ctx,shape)=>{const used=drawKind(ctx,shape);if(BRITISH_HERITAGE_KINDS.has(ctx.k)){const g=[ctx.W,ctx.O,ctx.D].find(g=>g[field].length);g[field][0]+=.01;}return used;});for(const{k}of BRITISH_HERITAGE)assert.notDeepEqual(changed[k],gold.kinds[k]);}});
 test('all saved variants finite/nondegenerate, exact H/parcel/owner, each ≤1300 triangles',()=>{for(const{k}of BRITISH_HERITAGE)for(let v=0;v<9;v++){const s=KT.size(k),r=drawOne(KT,looks,k,1,v,s),pos=r.G.flatMap(g=>g.pos);assert.ok(pos.length/9>100&&pos.length/9<=1300,k+' triangle budget');assert.ok(pos.every(Number.isFinite));let top=0;for(let j=0;j<pos.length;j+=3){assert.ok(pos[j]>=-1e-7&&pos[j]<=s+1e-7&&pos[j+2]>=-1e-7&&pos[j+2]<=s+1e-7,k+' parcel');assert.ok(pos[j+1]>=-1e-7&&pos[j+1]<=r.H+1e-7,k+' height');top=Math.max(top,pos[j+1]);}assert.ok(Math.abs(top-r.H)<1e-7);for(const g of r.G){assert.equal(g.owners.length,g.pos.length/9);assert.ok(g.owners.every(o=>o===1));for(let j=0;j<g.pos.length;j+=9){const a=g.pos.slice(j,j+3),b=g.pos.slice(j+3,j+6),c=g.pos.slice(j+6,j+9),u=b.map((x,i)=>x-a[i]),w=c.map((x,i)=>x-a[i]);assert.ok(Math.hypot(u[1]*w[2]-u[2]*w[1],u[2]*w[0]-u[0]*w[2],u[0]*w[1]-u[1]*w[0])>1e-10,k+' nondegenerate');for(let i=j;i<j+9;i+=3)assert.ok(Math.hypot(...g.nor.slice(i,i+3))>.99);}}assert.deepEqual(r.trees,[]);}});
 test('Jumbo is an open masonry arcade; opaque-infill mutation fails across all arenas',()=>{const r=drawOne(KT,looks,10,1,0,1);for(const x of[.4,.5,.6])assert.ok(opening(r,x,.3));for(const arena of['W','O','D']){const blocked=drawOne(KT,looks,10,1,0,1,undefined,(ctx,shape)=>{const used=drawKind(ctx,shape);ctx[arena].box(.2,.8,.8,.82,0,ctx.H*.5,new THREE.Color('#a45e45'),null,null);return used;});assert.equal(opening(blocked,.5,.3),false);}});
 test('deterministic and read-only inputs; no change to gameplay/source bytes outside reversible art dispatch',()=>{const input=JSON.stringify([KT.data,looks]);assert.deepEqual(kindHashes(),now);assert.equal(JSON.stringify([KT.data,looks]),input);assertD057Scope();});
 test('source allowlist rejects gameplay, existing D056 art, new art and dispatch mutations',()=>{for(const file of['src/sim/day.ts','src/io/save.ts','src/render/britishCivicArt.ts','src/render/britishHeritageArt.ts','src/render/kindArt.ts','src/cityView.ts'])assert.throws(()=>assertD057Scope(f=>fs.readFileSync(path.join(ROOT,f),'utf8')+(f===file?'\n// unauthorized mutation':'')),/exact allowed source/);});
 return failures;
}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){if(process.argv.includes('--write-golden')){const all=kindHashes();fs.writeFileSync(path.join(ROOT,'fixtures/d057-current-art.json'),JSON.stringify({baseline:'3330f0485cf8e37a40917f04ba16f7fa2d432639',kinds:Object.fromEntries(BRITISH_HERITAGE.map(({k})=>[k,all[k]]))},null,2)+'\n');}else process.exitCode=(await d057Guards((ok,n,d)=>console.log(ok?'PASS':'FAIL',n,d??'')))?1:0;}
